# ./Rocket.toml

[default]
name = "Erlon"
age = 31

[global]
address = "0.0.0.0"

[global.databases.db1]
url = "postgres://postgres:example@db1:5432/postgres"

[global.databases.db2]
url = "postgres://postgres:example@db2:5432/postgres"

# [global.databases]
# primary = { url = "postgres://postgres:example@db1:5432/db1", pool_size = 10 }
# secondary = { url = "postgres://postgres:example@db2:5432/db2", pool_size = 10 }
